### ISSUE TITLE
Roadmap for next version

### ISSUE THREAD

**Issue by cometkim** [cometkim/gatsby-plugin-typegen#27]
- [ ] Type definitions for schema customization
- [ ] ~~dts output support~~ #24
- [ ] ~~Auto-import~~ #16 
- [ ] Enhanced support for page queries? #74 
- [ ] E2E test
- [ ] Multiple languages configuration

**Comment by cometkim** [comment]
Have to consider about #36

**Comment by cometkim** [comment]
Contributing to the core is the correct way than providing 3rd type definitions since [GatsbyJS started to use TypeScript](https://github.com/gatsbyjs/gatsby/issues/21995). And I have to reconsider internal type definitions and utility types to depend on the core.

**Comment by cometkim** [comment]
According to the guideline:

> Lastly and most imporantly, we want to have simple types whenever possible. Primarily we should avoid Generics. Generic code can be highly reusable, but that can also come with the greater chance of breaking things. Code should be simple when possible. DRY is not always best.

Gatsby avoids type inference, and it's quite reasonable for that size of codebase.

However, we can still provide utilities for plugin/theme authors who want improved type inference. Perhaps it will be in a separate project.

**Comment by cometkim** [comment]
Move discussions here to #174
